name: 'Sphinx Publisher'
author: 'Kaijie Yu'
description: |-
  Deploy Sphinx source files as Github Pages. Multi-languages can be
  handled by providing langs.

branding:
  icon: 'globe'
  color: 'white'

inputs:
  source_root:
    description: "Root directory of source to build, default: 'docs/sources'."
    required: false
    default: 'docs/sources'
  build_root:
    description: "Root directory for build output, default: 'docs/build'."
    required: false
    default: 'docs/build'
  default_lang:
    description: |-
      The default language, which will be placed under the build directory,
      no subdirectory will be created. Default is 'en'.
    required: false
    default: 'en'
  lang_mappings:
    description: |-
      Newline-separated list of folder & language mappings to build.
      e.g.,
        en:en
        zh-Hans:zh_CN
      If you don't provide one, will just build for `default_lang`.
    required: false
    default: ''

outputs:
  page_url:
    description: 'URL to deployed GitHub Pages.'
    value: ${{ steps.deployment.outputs.page_url }}

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build static pages
      uses: Kjuly/sphinx-builder@main
      with:
        source_root: ${{ inputs.source_root }}
        build_root: ${{ inputs.build_root }}
        default_lang: ${{ inputs.default_lang }}
        lang_mappings: ${{ inputs.lang_mappings }}
    - name: Setup Pages
      uses: actions/configure-pages@v5
    - name: Upload Pages Artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: '${{ github.workspace }}/build/html'
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
